terrapkg/packages

anda/games/prismlauncher/prismlauncher.spec

missed an underscore in my previous macro for qt5 dependencies on opensuse, so now it works :)
also added support for rhel and centos being the build platform, as well as added some spacing so the endless if statements don't look too messy
this now mirrors what is on the repo i use for copr (or will when i push it there anyways), as well as the OBS, so it'll make my life a little easier. leaves the door open for building copr packages directly from this repo too

[prismlauncher] improve spec readability and compatibility

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/prismlauncher.spec

the only thing affecting packaging here is adding proper conflicts so that none of the packages can be installed together. this might change later with a patch since it was suggested in the prism discord, but i'm a little lazy
the rest is just making the specs as consistent as possible between each other, just so they all look nice :p

[prismlauncher] update conflicts/make specs more consistent

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/prismlauncher.spec

fixes rpmlint warnings and makes the entries on repology look better

add prismlauncher to Amusements/Games

---

anda/games/prismlauncher-nightly/fix-disable-FLOAT16-in-toml.patch
anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/fix-disable-FLOAT16-in-toml.patch
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/fix-disable-FLOAT16-in-toml.patch
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/fix-disable-FLOAT16-in-toml.patch
anda/games/prismlauncher/prismlauncher.spec

this PR fixes building on aarch64 for the stable releases, as well as bumping the tomlplusplus version in nightly builds. all of them use [this patch](https://github.com/flathub/org.prismlauncher.PrismLauncher/blob/master/0002-fix-disable-FLOAT16-in-toml.patch) from Scrumplex that addresses issues found in the revision of tomlplusplus used upstream (see https://github.com/marzer/tomlplusplus/issues/178)
[build on copr](https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/build/5041814/)

fix building prismlauncher on aarch64 with newer tomlplusplus version

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

not really sure what's going on, but it looks like auto updates are no longer working for the nightly packages. since the script still works for me locally and each check after discord-ptb fails, i'm guessing maybe there's some rate limiting going on here. is there any way to solve this?

[prismlauncher-nightly] bump commit

---

CODEOWNERS
anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/prismlauncher.spec

some changes include:
- more closely following fedora packaging guidelines by using pkgconfig for zlib and the system version of `filesystem`
- adding java 8 as a dependency for older versions of minecraft
- changing the versioning system for nightly packages to the way described [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_snapshots)
- adding myself to the CODEOWNERS file 
amazing work on the new documentation by the way! 😄

adopt new policies for prismlauncher

---

.github/workflows/update.yml

Git's documentation on using an SSH key for signing... isn't really helpful. I tried this in a container, and it should work... hopefully

Fix update action (again)

---

.github/workflows/update.yml

I'm pretty sure it should, but GitHub doesn't create the runner.temp directory before use. So let's do that here

Create runner.temp before use

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

upstream bumped the version in https://github.com/PrismLauncher/PrismLauncher/commit/4f3786c2e11f266a06e5a8281bfa16087c5dd42e
Signed-off-by: seth <getchoo@tuta.io>

[prismlauncher-nightly] bump version to 7.0

---

anda/lib/argagg/anda.hcl
anda/lib/argagg/argagg.spec
anda/lib/libappimageupdate/anda.hcl
anda/lib/libappimageupdate/libappimageupdate.spec
anda/lib/nlohmann-json/anda.hcl
anda/lib/nlohmann-json/nlohmann-json.spec
anda/tools/appimagelauncher/appimagelauncher.spec

This PR adds `libappimageupdate` and fixes AppImageLauncher, adding back postinstall and postuninstall scripts and fixes the libappimageupdate dependency.

Fix AppImageLauncher package

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

the qt5 build places qlogging categories to `/usr/share/qlogging-categories5`, not 6

[prismlauncher-nightly] add qlogging categories

---

anda/games/prismlauncher-nightly/0001-find-cmark-with-pkgconfig.patch
anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/0001-find-cmark-with-pkgconfig.patch
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

took me a while to figure this out, but it looks like fedora's `cmark-devel` package is at version that doesn't support cmake properly. this adds a patch that will remedy this issue with a new cmake config file sourced from [neochat](https://invent.kde.org/network/neochat/-/blob/3f8d2a11d0e00e35a743996b7f3e71c9a401de81/cmake/Findcmark.cmake)

[prismlauncher(-qt5)-nightly] add patch to find cmark correctly

---

anda/tools/lorax/anda.hcl

There's a bug in Anda where the `spec` option is not ignored when `enable_scm` is set, this is a temporary fix for that

Add blank spec to address Anda bug

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

tests currently fail on x64 for unknown reasons. this isn't reproducible on upstream's ci as well as building locally. not sure what's going on so it's better to just disable them for now since it seems to be a false positive.
also made cmark an explicit `requires` due to [this](https://bugzilla.redhat.com/show_bug.cgi?id=2166815) bug. i'll revert it once the change makes it way to f38

[prismlauncher-nightly] disable tests and explicitly require cmark

---

anda/rust/pop-launcher/pop-launcher.spec

Last time I incorrectly uncommented that so yeah I mean the macro escape thingy

fix(dbgpkg): pop-launcher

---

anda/python/protobuf/python3-protobuf.spec

fix: protobuf

---

anda/lib/libappimageupdate/libappimageupdate.spec

Some files that was included may cause file conflicts with other packages. They have been excluded.
Fixes #316

fix(files): libappimageupdate

---

anda/others/lomiri-schemas/lomiri-schemas.spec

For some reason, in my personal computer (Fedora 37), the schemas compile fine without the patch and with it fail but in my VM (also Fedora 37) it fails without the patch (opposite of my computer). So **Please** test this before merge.

fix(lomiri-schemas): revert remove feature

---

anda/others/ubuntu-sdk/ubuntu-sdk.spec

For some reason `ubuntu-sdk` is also not in Terra so this PR should trigger a test build so I can sort out the issue.

chore(ubuntu-sdk): run test build

---

anda/desktops/lomiri/lomiri.spec

With this PR Lomiri can function enough by itself though there are still smaller issues like the top bar. 
As you can see, the background is black because the settings amanager can't change the background, and the top bar is missing icons because ayatana indicators have not fully been done (still need to make/do more!).

fix(lomiri): update commit and get working

---

anda/lib/unity-settings-daemon/unity-settings-daemon.spec

For some reason rpmlint thinks we are running `configure` but we are only editing part of `configure.ac`.

fix(unity-settings-daemon): remove rpmlint warning

---

anda/lib/nux/nux.spec

Should remove the complaint from linter that the patch isn't applied even though it is.

chore(nux): change binary diff to source

---

anda/lib/lomiri-api/lomiri-api.spec
anda/lib/lomiri-api/update.rhai

Please note that the `update.rhai` does not update the commit and doesn't really change the version (it also would have already done it).

upd(lomiri-api): fb0956064460cb8b9e98cf8f450ddfad0326bfec
