terrapkg/packages

anda/prismlauncher/prismlauncher.spec

bump spec and remove unneded conflicts

---

anda/prismlauncher/prismlauncher.spec

this is a bit bigger than the last few PRs. the spec file has been majorly overhauled, based on the spec file from the games:tools repo on openSUSE. here's a quick list of changes:
- opensuse support
- build deps are now simplified and more modular (they use more variables :p)
- the giant license comment has been removed
- it wasn't needed on openSUSE, so i doubt it's needed here
- MSA ID and curseforge api keys are now variables
- the build platform is now correctly specified
- the package will be built against qt6 using %bcond_without 
- naming is confusing, but it will allow for building on older versions of rpm to understand it
- changelog has been edited
- all of my bumps were messy and unneeded, versions have also been changed to reflect the scheme from the final git commit release …

[prismlauncher] update to 5.0-3

---

anda/prismlauncher/change-jars-path.patch
anda/prismlauncher/prismlauncher.spec

silly package names are silly
also you're welcome for more commit spam

(╯°□°）╯︵ ┻━┻

---

anda/games/prismlauncher-nightly/anda.hcl
anda/games/prismlauncher-nightly/chkupdate.py
anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/anda.hcl
anda/games/prismlauncher-qt5-nightly/chkupdate.py
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

setting the copr packages to build from here once this is merged :)

add nightly builds for prismlauncher and prismlauncher-qt5

---

anda/games/prismlauncher-qt5/anda.hcl
anda/games/prismlauncher-qt5/change-jars-path.patch
anda/games/prismlauncher-qt5/chkupdate.py
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec

[build succeeded on copr](https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/build/4993851/)
i also have nightly packages up, but im going to talk to cappy about how chkupdate.py could be used for commits instead of releases, after that i'll merge them as well - and probably start building the copr packages from here because dear god i don't want to run my own script manually every night and stuff

add prismlauncher qt5

---

anda/games/prismlauncher-nightly/chkupdate.py
anda/games/prismlauncher-qt5-nightly/chkupdate.py

welp...forgot to uncomment the actually important line after testing the script :/

[primslauncher-nightly] epic comment fail

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

do i know what `modrinth-mrpack-mime.xml` does? no
but now the packages build :)

update installed files for primslauncher nightly builds

---

anda/tau-helium/tau-helium.spec

Found a He.NavigationRail styling error, am fixing it.

Bump tau-helium

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/prismlauncher.spec

fix conflicts (again)

---

README.md

Currently it's a bit barren, but I'll update it once I'm done writing our policies.

Add a bit more detail to our README

---

.github/PULL_REQUEST_TEMPLATE/new_package.md

Signed-off-by: lleyton <lleyton@fyralabs.com>

PR Templates

---

.github/workflows/update.yml

gpg.signingkey -> user.signingkey

Fix incorrect Git config in update workflow

---

anda/adwaita++-icons/chkupdate.py
anda/apps/openasar-canary/chkupdate.py
anda/apps/openasar-canary/openasar-canary.spec
anda/desktops/budgie/budgie-extras/chkupdate.py
anda/moby-extras/moby-buildx/chkupdate.py
anda/moby-extras/moby-compose/chkupdate.py
anda/rust/bat-extras/chkupdate.py
anda/rust/pop-launcher/chkupdate.py
anda/rust/sccache/chkupdate.py
anda/rust/youki/chkupdate.py
anda/rust/zellij/chkupdate.py
anda/tools/appimagelauncher/chkupdate.py
anda/tools/gcm-core/chkupdate.py

adds a chkupdate.py script to 12 out of the 33 (applicable by my count :p) packages listed in #26
maybe i'll work on some others later, these were just the easiest to add tonight

add chkupdate.py to more packages

---

.github/workflows/update.yml

Signed-off-by: seth <getchoo at tuta dot io>

set strict permissions for signing key

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/prismlauncher.spec

not relevant to terra itself, but since i use these to build on copr, i kinda need this.
also apparently the opensuse wiki is wrong about macros for rhel and centos 😵‍💫

support EPEL and F35 (again)

---

.github/workflows/update.yml

Signed-off-by: seth <getchoo@tuta.io>

enable terra repo to install anda

---

anda/desktops/elementary/elementary-capnet-assist/elementary-capnet-assist.spec
anda/desktops/elementary/elementary-music/elementary-music.spec

Fix broken elementary packages

---

anda/tools/lorax/anda.hcl

Yes, I know that we're going to remove this soon, but might as well bump it for now.

Bump Lorax

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/prismlauncher.spec

see https://github.com/PrismLauncher/PrismLauncher/issues/646

replace headless java with full package in prismlauncher

---

anda/rust/zellij/rust-zellij.spec

Bump rust-zellij

---

anda/rust/sccache/rust-sccache.spec

Bump rust-sccache

---

.github/workflows/update.yml

Add verbosity to update pipeline

---

CODEOWNERS
anda.hcl
anda/tools/appimagelauncher/appimagelauncher.spec

Signed-off-by: Cappy Ishihara <cappy@cappuchino.xyz>
**What software is being packaged here?**
The name of the software and link to website (if it exists) and source code (if available).
**Describe the motivation**
A clear and concise description of why you want this package. Would this provide value to other users?
**Additional context**
Add any other context about the package submission here. Link to any relavent issues.

Update appimagelauncher, make use of new anda directives

---

anda/lib/argagg/argagg.spec

**What software is being packaged here?**
The name of the software and link to website (if it exists) and source code (if available).
**Describe the motivation**
A clear and concise description of why you want this package. Would this provide value to other users?
**Additional context**
Add any other context about the package submission here. Link to any relavent issues.

fix libargagg

---

anda/rust/rnote/rnote.spec

Bump rnote 0.5.12

---

.github/workflows/update.yml
anda/fonts/iosevka-fusion/anda.hcl
anda/fonts/iosevka-fusion/iosevka-fusion-fonts.spec
anda/fonts/iosevka-fusion/iosevka-fusion.toml
anda/fonts/iosevka-fusion/update.rhai
anda/fonts/vl-gothic/65-2-vl-pgothic-fonts.conf
anda/fonts/vl-gothic/65-3-vl-gothic-fonts.conf
anda/fonts/vl-gothic/anda.hcl
anda/fonts/vl-gothic/vl-gothic-fonts.spec

I didn't get to test `iosevka-fusion-fonts`, somehow crashes my laptop thrice in a row. `vl-gothic-fonts` does build though.
close #85

Add iosevka-fusion-fonts vl-gothic-fonts

---

anda/fonts/manrope/.gitignore
anda/fonts/manrope/README.md
anda/fonts/manrope/anda.hcl
anda/fonts/manrope/manrope-fonts.spec

**What software is being packaged here?**
The name of the software and link to website (if it exists) and source code (if available).
**Describe the motivation**
A clear and concise description of why you want this package. Would this provide value to other users?
**Additional context**
Add any other context about the package submission here. Link to any relavent issues.

Add Manrope font

---

anda/apps/anki-bin/anki-bin.spec
anda/apps/anki-qt5/anki-qt5.spec
anda/apps/anki/anki.spec

Fix anki I swear this is last time

---

anda/apps/discord-canary/discord-canary.spec

Fuck debug source list

---

anda/tools/vala-language-server-nightly/anda.hcl
anda/tools/vala-language-server-nightly/update.rhai
anda/tools/vala-language-server-nightly/vala-language-server-nightly.spec

vala-language-server-nightly

---

anda/nim/choosenim/choosenim.spec

Fix choosenim

---

.github/workflows/autobuild.yml
.github/workflows/bootstrap-anda.yml
.github/workflows/bootstrap-subatomic.yml
.github/workflows/build.yml
.github/workflows/mass-rebuild.yml

Reverts terrapkg/packages#131
we're having issues with large SRPM uploads, we'll probably want some sort of resumable uploads system in subatomic

Revert "Upload SRPMs"

---

anda/apps/discord-canary-openasar/discord-canary-openasar.spec
anda/apps/discord-canary/discord-canary.spec
anda/apps/discord-ptb-openasar/discord-ptb-openasar.spec

Fix openasar

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec

ig the last one didn't actually work 🤷🏻 
used this locally, no more tests! :)

[prismlauncher-nightly] manually disable tests

---

anda/games/prismlauncher-qt5/0001-find-cmark-with-pkgconfig.patch
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/0001-find-cmark-with-pkgconfig.patch
anda/games/prismlauncher/prismlauncher.spec

continuation of https://github.com/terrapkg/packages/pull/161 and https://github.com/terrapkg/packages/pull/162
..i admit i forgor
i do `vim prismalauncher-*nightly/*.spec` most of the time in this repo so i guess muscle memory just got the better of me (and a bit of a brain fart)

[prismlauncher] (actually) update to 6.3

---

README.md

Add Repology badge

---

anda/desktops/elementary/wingpanel-indicator-power/wingpanel-indicator-power.spec

Fix wingpanel-indicator-power

---

anda/groovy/groovy-docs/groovy-docs.spec
anda/groovy/groovy.spec

Fix groovy groovy-docs

---

anda/go/xyproto-env/update.rhai
anda/go/xyproto-textoutput/update.rhai
anda/go/xyproto-vt100/update.rhai
anda/go/yhat-scrape/update.rhai

Fix update.rhai: xyproto-env xyproto-textoutput xyproto-vt100 (gh_tag)
Erase update.rhai: yhat-scrape (no version)

fix: update

---

anda/tools/graalvm/anda.hcl
anda/tools/graalvm/graalvm.spec
anda/tools/graalvm/update.rhai

Add graalvm

---

anda/tools/graalvm/update.rhai

fix(update): graalvm

---

anda/groovy/groovy-docs/update.rhai
anda/groovy/update.rhai

add(update): groovy

---

anda/groovy/groovy-docs/update.rhai
anda/groovy/update.rhai

fix(update): groovy groovy-docs

---

anda/fonts/nerd-fonts/nerd-fonts.spec

fix(deps): nerd-fonts

---

anda/rust/maturin/rust-maturin.spec

Trying to bump rust-packaging from >= 21 to 23
Signed-off-by: madomado <119111128+madonuko@users.noreply.github.com>

fix(deps): maturin

---

anda/games/osu-lazer/anda.hcl
anda/games/osu-lazer/osu-lazer-uri-handler.desktop
anda/games/osu-lazer/osu-lazer.desktop
anda/games/osu-lazer/osu-lazer.spec
anda/games/osu-lazer/update.rhai
anda/games/osu-mime/anda.hcl
anda/games/osu-mime/osu-file-extensions.xml
anda/games/osu-mime/osu-mime.spec
anda/rust/sccache/rust-sccache.spec
anda/rust/sccache/update.rhai

commit b0b62ae308197bd6cbab832a5e915a8ea152ecd5
Merge: c8c13b7 fcb92e1
Author: windowsboy111 <wboy111@outlook.com>
Date:   Mon Feb 13 17:25:16 2023 +0800
Merge branch 'main' into osu-lazer
commit c8c13b724749ff560727fb02912f1ca701e26f29
Author: windowsboy111 <wboy111@outlook.com>
Date:   Mon Feb 13 17:22:19 2023 +0800
lint: osu-lazer
commit 5aac8e807add521785515762f15e2c8803a0c20b
Author: windowsboy111 <wboy111@outlook.com>
Date:   Mon Feb 13 17:21:25 2023 +0800
lint: osu-mime
commit a1b44acfb29414174c56d7e11f5bf275d080f4c5
Author: windowsboy111 <wboy111@outlook.com>
Date:   Mon Feb 13 17:20:00 2023 +0800
fix(update): sccache
commit …

add: osu-lazer osu-mime

---

anda/python/protobuf/python3-protobuf.spec

fix: protobuf

---

.github/workflows/update.yml

Part of the investigation on the error here: https://github.com/terrapkg/packages/actions/runs/4205239359/jobs/7297028162

feat(gha): update workflow show full backtrace

---

anda/desktops/compiz9/compiz9.spec

Fix building compiz

---

anda/lib/libindicator/libindicator.spec

fix: fix libindicator

---

anda/lib/libindicator/libindicator.spec

fix: add systemd pkgconfig

---

anda/lib/marble-gtk/anda.hcl
anda/lib/marble-gtk/marble-gtk.spec
anda/lib/marble-gtk/update.rhai

marble-gtk was accidentally removed in commit 4600a1dc654d4070d1d481a19e64160ac1956052

add: marble-gtk

---

CODEOWNERS
anda/lib/glewmx/anda.hcl
anda/lib/glewmx/glewmx.spec

feat: add glewmx

---

anda/lib/libunity-misc-devel/anda.hcl
anda/lib/libunity-misc/anda.hcl
anda/lib/libunity-misc/libunity-misc.spec

I accidently forgot to split the package and do some other improvements.

chore: split libunity-misc

---

anda/lib/libunity-misc/libunity-misc.spec

Also unity-settings-daemon should work as I can build it.

upd: libunity-misc 4.0.5

---

anda/lib/glewmx/glewmx.spec

Hopefully this will work. This is what Ubuntu does.

Hopefully fix glewmx on aarch64

---

anda/lib/geis/anda.hcl
anda/lib/geis/geis.spec

**Before this is merged, some packages must be rebuilt!**

feat: add geis

---

anda/others/unity-scope-home/anda.hcl
anda/others/unity-scope-home/unity-scope-home.spec

Add unity-scope-home

---

anda/desktops/unity-shell/0001-Remove-xpathselect-dependency.patch
anda/desktops/unity-shell/0002-Remove-ido-dependency.patch
anda/desktops/unity-shell/0003-Remove-social-scope.patch
anda/desktops/unity-shell/anda.hcl
anda/desktops/unity-shell/unity-shell.spec

This still requires: unity-session and unity-scope-home to really be used.

Add unity-shell

---

anda/others/unity-session/anda.hcl
anda/others/unity-session/unity-session.spec

Add unity-session

---

anda/others/unity-greeter/unity-greeter.spec

fix(unity-greeter): add unity-shell to Requires

---

anda/desktops/elementary/granite-7/granite-7.spec

fix(chks): granite-7

---

anda/desktops/unityx-shell/0001-Remove-social-scope.patch
anda/desktops/unityx-shell/anda.hcl
anda/desktops/unityx-shell/unityx-shell.spec

This is the last RPM spec from https://github.com/cat-master21/unityDE-specs. There are still some issues (primarilly with `compiz9`) that need to be solved. Unityx doesn't actually work mostly because of https://gitlab.com/ubuntu-unity/unity-x/unityx/-/issues/6.

feat: add unityx-shell

---

anda/lib/lomiri-api/anda.hcl
anda/lib/lomiri-api/lomiri-api.spec

The beginning PR to add Lomiri to Terrapkg.

Feat: add Lomiri-api

---

anda/lib/qt5-pim/anda.hcl
anda/lib/qt5-pim/qt5-pim.spec

Fun fact: Fedora packages the 5 year old qt4 version of pim.

feat: add qt5-pim

---

anda/lib/lomiri-ui-toolkit/anda.hcl
anda/lib/lomiri-ui-toolkit/lomiri-ui-toolkit.spec

Depends on #284 and #283 first.

feat: add lomiri-ui-toolkit

---

anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
anda/games/prismlauncher/prismlauncher.spec

solves #287 by adding `flit` to `Recommends` in order to support narrator in minecraft

[prismlauncher]: recommend flite

---

anda/lib/qtdbusmock/anda.hcl
anda/lib/qtdbusmock/qtdbusmock.spec

Feat: add qtdbusmock

---

anda/lib/ayatana-indicator-datetime/anda.hcl
anda/lib/ayatana-indicator-datetime/ayatana-indicator-datetime.spec

Depends on #327 first to build.

feat: add ayatana-indicator-datetime

---

anda/lib/ayatana-indicator-messages/anda.hcl
anda/lib/ayatana-indicator-messages/ayatana-indicator-messages.spec

Depends on #326 first to build.

feat: add ayatana-indicator-messages

---

anda/desktops/lomiri/0001-Add-support-for-both-older-qtmir-and-newer-qtmir-wit.patch
anda/desktops/lomiri/anda.hcl
anda/desktops/lomiri/lomiri.spec

`lomiri-session` is needed to use a display manager.

feat: add lomiri

---

anda/others/lomiri-session/anda.hcl
anda/others/lomiri-session/lomiri-session.spec

The final RPM from https://github.com/cat-master21/lomiri-specs :confetti_ball:

feat: add lomiri-session

---

anda/kotlin/kotlin-native/anda.hcl
anda/kotlin/kotlin-native/kotlin-native.spec
anda/kotlin/kotlin-native/update.rhai
anda/kotlin/kotlin/anda.hcl
anda/kotlin/kotlin/kotlin.spec
anda/kotlin/kotlin/update.rhai

feat: kotlin & kotlin-native

---

anda/lib/libindicator/libindicator.spec

chore(libindicator): remove linting warning

---

anda/kotlin/kotlin-native/kotlin-native.spec
anda/kotlin/kotlin/kotlin.spec

This is my last PR and should fianlly remove the rpmlint warnings from Terra.

fix(kotlin): remove rpmlint warnings
